package:
  name: 'nionswift-instrumentation'
  version: '23.2.1'

source:
  git_rev: 23.2.1
  git_url: https://github.com/nion-software/nionswift-instrumentation-kit.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.11
    - niondata >=15.8,<16.0
    - nionswift >=16.13,<17.0
    - nionui >=9.0,<10.0
    - nionutils >=4.13,<5.0
    - numpy >=2.0,<3.0

test:
  imports:
    - nion.device_kit
    - nion.instrumentation
    - nion.instrumentation.test
    - nionswift_plugin.nion_instrumentation_ui

about:
  home: https://github.com/nion-software/nionswift-instrumentation-kit
  license: GPL-3.0
  summary: "A Nion Swift library for STEM instrumentation (Camera, Scan, Video, Microscope)."
  description: "A Nion Swift library for STEM instrumentation (Camera, Scan, Video, Microscope)."

extra:
  recipe-maintainers:
    cmeyer
